name = "XLSXDecrypt"
uuid = "e3fae58b-f948-45ca-982d-29fa61c37f2f"
license = "MIT"
version = "0.1.0"
authors = ["Tim Gebbels <timgbbels@gmail.com>"]
description = "Access password protected .xlsx files"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
Base64 = "1.11.0"
Nettle = "1"
SHA = "0.7.0"
XML = "0.3"
julia = "1.10"
